### ISSUE TITLE
Unable to use kuberesolver with go modules since addition of go.mod

### ISSUE THREAD

**Issue by bmhatfield** [sercand/kuberesolver#11]
I am not 100% sure what to do about this, but the error message is:
 > module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

And the relevant Go issue is: https://github.com/golang/go/issues/35732

I believe the root of the problem is that the import path does not end in `/v2`, but the tag is `v2.3.0`. This was previously fine because there was no `go.mod` on this repo, allowing for the use of `+incompatible`, but now that the repo has a `go.mod`, that does not work anymore.

I was able to temporarily work around this by using a computed version without referencing the tags, but it's sad to lose that version metadata.

**Comment by sercand** [comment]
@bmhatfield Thanks for the report. I will be looking this today.

**Comment by sercand** [comment]
I removed go.mod and released v2.4.0
