### ISSUE TITLE
Does kuberesolver watch all endpoints?

### ISSUE THREAD

**Issue by pselden** [sercand/kuberesolver#13]
If I use `RegisterInCluster` does it automatically watch all endpoints? If so, is there a way to make it so it only watches certain endpoints? My cluster has tons of stuff in it and I only need it to watch one.

**Comment by sercand** [comment]
@pselden Sorry for the late response.
When you dial with
```
grpc.Dial("kubernetes:///service-name.namespace:portname")
```
it watches **only** the `service-name` and it gives all endpoints to gRPC and gRPC connects one of them by default.

If you want to connect all service endpoints and do client-side load-balancing to achieve high availability you need pass balancer option to dial.

For example: 
```
grpc.Dial("kubernetes:///service-name.namespace:portname", grpc.WithBalancerName("round_robin"))
```

I hope this helps.
