### ISSUE TITLE
Use pod's namespace instead of default

### ISSUE THREAD

**Issue by okgolove** [sercand/kuberesolver#15]
Hello!
Thanks for the library, it's really very helpful!

I'd like to ask about using `default` namespace in case of we do not set `namespace` in url string, for example:
```
kubernetes:///test:8090
```

In this case `default` namespace will be used to get endpoints.

Is there a reason to use `default` namespace? Shouldn't we get pod's namespase from file  `/var/run/secrets/kubernetes.io/serviceaccount/namespace`?

**Comment by sercand** [comment]
@okgolove released [v3.0.0](https://github.com/sercand/kuberesolver/releases/tag/v3.0.0) to address this issue. Since it changes existing behavior, bumped the version number to 3.
