### ISSUE TITLE
Question about reconnection and context

### ISSUE THREAD

**Issue by Azuka** [sercand/kuberesolver#20]
How well does this perform when using `grpc.DialContext()`? ie if a connection was established then the endpoints change, is the connection restablished using the original context which might have a cancellation signal?

I'd love to use this, if only to prevent errors like `rpc error: code = Unavailable desc = transport is closing`

**Comment by sercand** [comment]
@Azuka this library provides IP addresses to gRPC and establishing and canceling connections done by gRPC itself. When the endpoint IP addresses change it informs gRPC about the change and gRPC establishes new connections. If you use a balancer like `grpc.WithBalancerName("round_robin")`  and kubernetes liveness/readiness probes, you will achieve zero downtime connections with the target service. To summarise, DialContext is handled by gRPC.
