### ISSUE TITLE
Document ServerName 

### ISSUE THREAD

**Issue by GauntletWizard** [sercand/kuberesolver#23]
This is non-obvious and took me a bit to figure out: The ‘ServerName’ attribute of [resolver.Address](https://pkg.go.dev/google.golang.org/grpc/resolver#Address)es that KubeResolver returns is ([generally](https://github.com/sercand/kuberesolver/blob/master/builder.go#L227)) set to the pod’s name. This means that if you are using KubeResolver with MTLS, you need a cert signed to the pod specifically. Not coincidentally, I’ve built a [tool](https://gitlab.com/gauntletwizard_net/kubetls) that does just that

This is reasonable default behavior, though I’d also like to see the ability to leave the hostname as `servicename`, or `service-name.namespace` - These make sense as naming behaviors, and match what you would expect if you’re already connecting via cluster DNS.

**Comment by sercand** [comment]
After the release of [v3.1](https://github.com/sercand/kuberesolver/releases/tag/v3.1) the ServerName is set to `service-name.namespace`
