### ISSUE TITLE
Question about TLS and certificates

### ISSUE THREAD

**Issue by renatojf** [sercand/kuberesolver#25]
Hey guys, I recently added `kuberesolver` to my project but unfortunately I cannot make it work properly.
I created a headless service in k8s, added the DNS to my TLS certificates, but when I fire a request from a pod to another pod running the gRPC server, it throws me this error:

```
transport: authentication handshake failed: x509: certificate is valid for my-service-headless, not my-service-c9bd84f49-fjgg8
```

This means that it is resolving the headless pods, and firing the requests directly to them, bypassing the DNS names in the certificates.

Not sure if I managed to explain that properly, sorry
Does anyone has any clue on how to solve this? I even tried to force the `Host` header in the gRPC request to bypass this, but with no success :(

**Comment by renatojf** [comment]
A little bit more info on this, as I still can't connect properly :(

- If I use `kubernetes:///my-service-headless:3000`, I get the error above
- If I use `kubernetes://my-service-headless:3000`, I get the error saying that there are too many colons in the address (although I do have the `RegisterInCluster()` statement before the Dial)
- If I use `kubernetes://ns/my-service-headless:3000` I also get the error about authentication handshake failure 

I dunno what else to do :(

**Comment by sercand** [comment]
@renatojf This is about the issue #23. I just released [v3.1](https://github.com/sercand/kuberesolver/releases/tag/v3.1) to address this issue. From now on you can use self-signed certificates with my-service.namespace name.

**Comment by renatojf** [comment]
Thank you so much for the patch @sercand, but unfortunately I cannot test it, as `go.mod` fails to recognize your latest version. I think you need to use `major.minor.patch`. Would you kindly do another release?

**Comment by sercand** [comment]
@renatojf Sorry about the release. I just released a new version.

**Comment by renatojf** [comment]
@sercand tested and works flawlessly. Thank you so much once again!
