### ISSUE TITLE
how to debug on localhost?

### ISSUE THREAD

**Issue by MikyChow** [sercand/kuberesolver#26]
i want to debug on my mac,i am using port-forward , but it seems can't connect to k8s,

**Comment by labulaka521** [comment]
https://github.com/sercand/kuberesolver/blob/master/kubernetes.go#L61
you need set env `KUBERNETES_SERVICE_HOST` and  `KUBERNETES_SERVICE_PORT ` and set token and ca

token and ca could look it in kubectl config like `~/.kube/config`

**Comment by sercand** [comment]
You can register kuberesolver to gRPC resolver with following:

```go
resolver.Register(kuberesolver.NewBuilder(kuberesolver.NewInsecureK8sClient("http://localhost:8081"), "kubernetes"))
```
