### ISSUE TITLE
grpc resolver.ClientConn NewAddress method is deprecated

### ISSUE THREAD

**Issue by GoosvandenBekerom** [sercand/kuberesolver#30]
While looking through the code to understand it a bit better I saw that a deprecated method of the resolver.ClientConn interface is being used here https://github.com/sercand/kuberesolver/blob/master/builder.go#L240

https://pkg.go.dev/google.golang.org/grpc/resolver#ClientConn states that UpdateState should be used instead

![image](https://user-images.githubusercontent.com/15077412/195803536-15213b10-b780-44c2-9733-317b3f5ec398.png)

**Comment by philipgriggs** [comment]
@sercand There's a few places where deprecated code from `google.golang.org/grpc` is being used (for example [here](https://github.com/sercand/kuberesolver/blob/8092c78a8fcf8ca43dc1b3fb55a3891a430a5c3f/builder.go#L235)). This breaks upstream dependencies when the version is set to `google.golang.org/grpc v1.58.0`

See [github.com/grpc/grpc-go/releases/tag/v1.58.0](https://github.com/grpc/grpc-go/releases/tag/v1.58.0)

>resolver: remove deprecated AddressType (https://github.com/grpc/grpc-go/pull/6451)
>
> This was previously used as a signal to enable the "grpclb" load balancing policy, and to pass LB addresses to the policy. Instead, balancer/grpclb/state.Set() should be used to add these addresses to the name resolver's output. The built-in "dns" name resolver already does this.

I think this line could just be removed
