### ISSUE TITLE
connection errors during watch do not cause a reconnect

### ISSUE THREAD

**Issue by butonic** [sercand/kuberesolver#53]
AFAICT `kubeBuilder.Build` should reconnect when the witcher encounters an error:
https://github.com/sercand/kuberesolver/blob/b38284655159370a46e71c751f1fe09f99fcec0b/builder.go#L177-L183

But `tkResolver.watch()` only returns an error during the initial connection establishment in `watchEndpoints()`. All other cases in the select return a nil error:
https://github.com/sercand/kuberesolver/blob/b38284655159370a46e71c751f1fe09f99fcec0b/builder.go#L278-L299

`watchEndpoints` sets up a `newStreamWatcher` which loops over the channel and closes it in case of an error:
https://github.com/sercand/kuberesolver/blob/b38284655159370a46e71c751f1fe09f99fcec0b/stream.go#L69-L93

`until()` only wraps panics ... and will silently stop restarting watch() after 30secs

Am I missing something? How does the actual reconnect happen on intermediate connection errors after the 30 seconds? There is a timer that updates the endpoints every 30min, but the watcher is just not restarted.

I'm asking because we encountered the kubernetes API to be unavailable for minutes during a cluster upgrade.

**Comment by sercand** [comment]
> until() only wraps panics ... and will silently stop restarting watch() after 30secs

No, this is wrong. `until` always calls the given function with backoff and never stops recalling until given stop channel called. The backoff sequence is 1, 2, 4, 8, 16, 30, 30, 30... seconds

**Comment by butonic** [comment]
Ah, I double checked the codepath of the channel handed to until. I somewhere mixed it up with the cancel channel of the streamWatcher. Thx for clarifying and sorry for the noise.
